;;; gptel-annotate.el --- Annotate files or buffers with LLMs  -*- lexical-binding: t; -*-

;; Copyright (C) 2026  Karthik Chikmagalur

;; Author: Karthik Chikmagalur <karthikchikmagalur@gmail.com>
;; Version: 0.0.5
;; Package-Requires: ((emacs "29.1") (compat "30.1.0.0") (gptel "0.9.9.5"))
;; Keywords: comm

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; `gptel-annotate' is an extension for `gptel' that allows you to use Large
;; Language Models (LLMs) to annotate buffers or files with suggestions,
;; warnings, or notes.  It usees Emacs' built-in Flymake minor mode to
;; display the LLM-generated diagnostics.
;;
;; Usage:
;;
;; To annotate a file or buffer, run `M-x gptel-annotate'.  This command prompts
;; for the instructions to send to the LLM and the target sources (files or
;; buffers) to annotate.  By default, it annotates the current buffer, but with
;; a prefix argument (`C-u') it lets you specify multiple buffers and files.
;;
;; When used in a regular chat session you can omit the instructions to read
;; them from the prompt in the chat buffer instead.
;;
;; In addition to the interactive command, `gptel-annotate' can be used
;; directly within any prompt by applying the `gptel-annotate'
;; preset, by inserting `@gptel-annotate' followed by file or buffer names in
;; the prompt.  For instance, consider this hypothetical prompt:
;;
;; ------------------------------------------------------------------------
;; *prompt*: Highlight any flaws in the design and architecture of the
;; work-in-progress gptel-annotate and gptel-flymake, ignoring any low level
;; issues that will be caught by the byte-compiler.
;;
;; @gptel-annotate gptel-annotate.el "gptel-flymake.el"
;; ------------------------------------------------------------------------
;;
;; When typed anywhere in Emacs and sent with `gptel-send', this request will
;; include the contents of the buffers (or files) gptel-annotate.el and
;; gptel-flymake.el, and the LLM's targeted responses will be displayed as
;; flymake annotations in these two buffers.  Using "quotes" around the
;; buffer/file names is recommended.
;;
;; You can also include the @gptel-annotate cookie without specifying any
;; buffers or files, and the LLM will attempt to annotate the right buffer based
;; on the conversation context.  This is useful if the LLM has already examined
;; the source location using tool calls in earlier turns.  Example:
;;
;; ------------------------------------------------------------------------
;; *prompt*: Provide a short summary of each link in the blog
;; post, along with a readability rating out of 10.  @gptel-annotate
;; ------------------------------------------------------------------------
;;
;; Presumably, it is clear in this context which buffer "blog post" refers to.
;;
;; The LLM's response is parsed, and annotations are automatically
;; applied to the relevant buffers as Flymake diagnostics.

;;; Code:

(require 'cl-lib)
(require 'gptel)
(require 'subr-x)
(require 'flymake)
(require 'thingatpt)

(defvar-local gptel-annotate--sources nil
  "List of sources (buffers or files) for which annotations are generated.
This is intended to be set buffer-locally or let-bound by
`gptel-annotate' at the time of request.")

(defvar-local gptel-annotate--diagnostics nil
  "Diagnostics generated by `gptel-annotate' for a buffer.")

(defconst gptel-annotate--response-buffer "*gptel-annotate*"
  "Buffer holding intermediate LLM responses (like reasoning).
Its main purpose is as a sink to avoid spewing text everywhere in
`gptel-annotate' requests.")

;;;; Flymake backend setup
(defun gptel-annotate--find-text-bounds (text)
  "Find bounds of TEXT near point heuristically."
  ;; TODO: Use word-search-forward/backward in text-mode bufs
  (or (and (or (save-excursion (search-forward text nil t))
               (search-backward text nil t))
           (cons (match-beginning 0)    ;word-search matches trailing whitespace
                 (progn (goto-char (match-beginning 0)) (end-of-line)
                        (min (point) (match-end 0)))))
      (when (length> text 80)      ;Heuristic: look for chunks and adjust bounds
        (cl-loop
         with chunk-size = (floor (length text) 3)
         with rem = (mod (length text) 3)
         for idx in '(1 2)
         for split-text =
         (word-search-regexp
          (substring text (* idx chunk-size) (* (1+ idx) chunk-size)) t)
         ;; Description of `word-search-regexp' is wrong; lax does handle word
         ;; boundary at front of text:
         if (string-prefix-p "\\<" split-text)
         do (setq split-text (substring split-text 2))
         if (or (save-excursion (re-search-forward split-text nil t))
                (re-search-backward split-text nil t))
         return (cons (- (match-beginning 0) (* idx chunk-size))
                      (+ (match-end 0) (* (- 2 idx) chunk-size) rem))))))

(defun gptel-annotate--make-diagnostics (array buffer &optional offset-beg)
  "Return a list of flymake diagnostics from ARRAY for BUFFER.

Start from char OFFSET-BEG if provided."
  (save-excursion
    (delq nil
          (mapcar
           (pcase-lambda ((map :start_line :text :diagnostic :replacement_text))
             (when (and diagnostic (not (string-empty-p diagnostic)))
               (goto-char (or offset-beg (point-min)))
               (forward-line (1- start_line))
               (and-let* (((stringp text))
                          (bounds (gptel-annotate--find-text-bounds text)))
                 (flymake-make-diagnostic
                  buffer (car bounds) (cdr bounds)
                  (if (and replacement_text
                           (not (string-blank-p replacement_text)))
                      :warning :note)
                  diagnostic (list diagnostic replacement_text)
                  `((flymake-gptel . t)
                    (mouse-face . highlight)
                    (keymap . ,flymake-gptel-actions-map))))))
           array))))

(defun gptel-annotate--flymake-setup (response info)
  "Start flymake with diagnostics from RESPONSE.

INFO is the request plist containing the source buffers for the
diagnostics."
  (let ((source-buffers))
    ;; ensure that the required files are open
    (dolist (source (ensure-list (plist-get info :context)))
      (cond
       ((and-let* ((source-buf (get-buffer source)))
          (if (buffer-live-p source-buf)
              (push source-buf source-buffers)
            (display-warning
             'gptel-annotate
             (format "Source buffer %s has been killed, aborting gptel annotation in this buffer"
                     source))
            nil)))
       ((if-let* (((file-readable-p source))
                  (buf (or (find-buffer-visiting source) (find-file-noselect source))))
            (push buf source-buffers)
          (display-warning
           'gptel-annotate
           (format "Source file %s not readable, aborting gptel annotation in this file"
                   source))))))

    ;; Set up flymake diagnostics in source buffers
    (when source-buffers
      (condition-case nil
          (progn
            (unless (string-match-p "\\`\\s-*{" response)
              ;; Try to handle partially schema-compliant responses
              (when-let* ((brace-start (string-search "{" response)))
                (setq response (substring response brace-start))))
            (let ((diag-array (plist-get (gptel--json-read-string response) :items))
                  (setup (lambda (buf arr)
                           "Create annotations in BUF from ARR."
                           (with-current-buffer buf
                             (setq gptel-annotate--diagnostics arr)
                             (add-hook 'flymake-diagnostic-functions
                                       #'flymake-gptel-annotate nil t)
                             (if flymake-mode (flymake-start nil t) (flymake-mode 1))))))
              (if (= (length source-buffers) 1) ;most common case
                  (funcall setup (car source-buffers) diag-array)
                ;; Sort diag-array elements by buffer and set up each one
                (cl-loop with diags-alist
                         for diag across diag-array
                         for dest = (let ((f (plist-get diag :file_name)))
                                      (or (get-buffer f)
                                          (find-buffer-visiting f)))
                         if dest do (push diag (alist-get it diags-alist))
                         finally do
                         (cl-loop for (buf . buf-diags) in diags-alist
                                  do (funcall setup buf (vconcat buf-diags)))))))
        (error
         (with-current-buffer (get-buffer-create gptel-annotate--response-buffer)
           (goto-char (point-max)) (insert response))
         (message "`gptel-annotate' could not parse LLM response. \
See buffer %s for the raw annotation"
                  (propertize gptel-annotate--response-buffer 'face 'bold)))
        (:success (message "gptel-annotations available in: %s"
                           (mapconcat (lambda (b) (propertize (buffer-name b) 'face 'bold))
                                      source-buffers ", "))
                  (run-hooks 'gptel-annotate-post-hook))))))

;;;; gptel request setup

(defun gptel-annotate--request-context (fsm)
  "Prepare the request in FSM for annotation.
Store `gptel-annotate--sources' as the request context and wrap the
existing callback (or the default gptel callback) with an
annotation-aware handler."
  (let* ((info (gptel-fsm-info fsm))
         (stream (plist-get info :stream))
         (cb (plist-get info :callback)))
    (plist-put info :context gptel-annotate--sources)
    (plist-put info :callback
               (if stream
                   (gptel-annotate--wrap-stream-callback
                    (or cb #'gptel-curl--stream-insert-response))
                 (gptel-annotate--wrap-callback
                  (or cb #'gptel--insert-response))))))

(defmacro gptel-annotate--call-inner (callback response info raw)
  "Call `gptel-request' CALLBACK with RESPONSE accounting for arity.

INFO is the request plist, RAW is used internally by `gptel-send' for
formatting parts of responses."
  ;; gptel-send's default callbacks have an arity of 3 because they call
  ;; themselves for inserting special blocks
  `(if (> (cdr (func-arity ,callback)) 2)
       (funcall ,callback ,response ,info ,raw) ;plumb everything else through
     (funcall ,callback ,response ,info)))

(defun gptel-annotate--wrap-callback (callback)
  "Wrap FSM's CALLBACK to annotate the required buffers or files."
  (lambda (response info &optional raw)
    (pcase response
      ((pred stringp)                   ;we take over (for annotation)
       ;; (funcall callback response info t) ;Debugging
       (gptel-annotate--flymake-setup response info))
      (_ (gptel-annotate--call-inner callback response info raw)))))

(defun gptel-annotate--wrap-stream-callback (callback)
  "Wrap FSM's streaming CALLBACK to annotate the required buffers or files."
  (let (accum-response)
    (lambda (response info &optional raw)
      (pcase response
        ((pred stringp)
         ;; (funcall callback response info 'raw) ;Debugging
         (push response accum-response))
        ('t                             ;Streaming is done
         (gptel-annotate--call-inner callback response info raw)
         (if-let* ((tool-use (plist-get info :tool-use)) ;Did we stop to run tools?
                   ((not (cl-some (lambda (call) (equal (plist-get call :name)
                                                   gptel--ersatz-json-tool))
                                  tool-use))))
             (setq accum-response nil)  ;Yes, so do nothing
           (gptel-annotate--flymake-setup
            (apply #'concat (nreverse accum-response)) info)
           (setq accum-response nil)))
        (_ (gptel-annotate--call-inner callback response info raw))))))

(cl-defun flymake-gptel-annotate
    (report-fn &key _recent-changes _changes-start _changes-end &allow-other-keys)
  "Report suggestions or errors generated by LLMs.

REPORT-FN is the flymake callback, see `flymake-diagnostic-functions'."
  (when gptel-annotate--diagnostics
    (funcall report-fn
             (gptel-annotate--make-diagnostics gptel-annotate--diagnostics
                                               (current-buffer)))))

(defvar gptel-annotate-response-schema
  '( :type object
     :properties
     ( :items
       ( :type array
         :minItems 0
         :items
         ( :type object
           :properties
           ( :file_name ( :type string
                          :description "Name of the file or buffer to which this diagnostic applies.")
             :start_line ( :type integer
                           :description "Starting line number of text to which this diagnostic applies")
             :text (:type string :description "Text to which this diagnostic applies")
             :diagnostic (:type string :description "Short description of the diagnostic.")
             :replacement_text ( :type string
                                 :description "Exact replacement text or fix for this diagnostic.  \
Must be left empty if no replacement is required and this is only a note.")))))))

(defun gptel-annotate-system-prompt-default ()
  "Create a system prompt instructing the LLM to annotate SOURCES."
  (format
   "\n\n<response_format>
To carry out the user's instructions, generate annotations for the %s \
file(s) or buffer(s)%saccording to the provided JSON schema.  \
These will be included as diagnostics (notes or linter-style suggestions) in the buffers.
</response_format>"
   (if gptel-annotate--sources "following" "relevant")
   (if gptel-annotate--sources
       (concat
        ":\n\n"
        (mapconcat
(lambda (source) (concat "- " (if (bufferp source) (buffer-name source) source)))
(ensure-list gptel-annotate--sources) "\n")
        "\n\n")
     " (deduced from context), ")))

(defvar gptel-annotate-system-prompt #'gptel-annotate-system-prompt-default)

(defun gptel-annotate--pre ()
  "Parse a file or buffer name at point into `gptel-annotate--sources'."
  (skip-syntax-forward " " (line-end-position))
  (while-let ((_ (not (or (eolp) (eobp))))
              (source (if (eq (char-after) ?\")
                          (read (current-buffer))
                        (prog1 (thing-at-point 'filename)
                          (goto-char (match-end 0))))))
    (skip-syntax-forward " " (line-end-position))
    (cl-callf substring-no-properties source)
    (cond
     ((file-readable-p source) (push source gptel-annotate--sources))
     ((buffer-live-p (get-buffer source))
      (push (get-buffer source) gptel-annotate--sources))
     (t (unless (or noninteractive
                    (y-or-n-p
                     (format "Cannot find source \"%s\" to @annotate, \
continue with gptel request? " source)))
          (user-error "gptel-annotate request aborted"))
      (message "Ignoring @annotate %s, file not readable" source))))
  gptel-annotate--sources)

(defun gptel-annotate--augment-system-prompt (sys)
  "Return a gptel system prompt function including annotation instructions.

SYS is the original system prompt, to be augmented."
  (lambda ()
    (list (concat (car (gptel--parse-directive sys 'raw))
                  (car (gptel--parse-directive
                        gptel-annotate-system-prompt 'raw))))))

(defvar gptel-annotate--preset
  (list
   :prompt-transform-functions
   `(:function ,(lambda (ptf) (cons #'gptel-annotate--request-context ptf)))
   :use-context 'system
   :context `(:function ,(lambda (context)
                           (if gptel-annotate--sources
                               (nconc gptel-annotate--sources context)
                             context)))
   :schema gptel-annotate-response-schema
   :system `(:function ,#'gptel-annotate--augment-system-prompt))
  "Base preset for `gptel-annotate' requests.

To be useful, this needs to be combined with some way of setting
`gptel-annotate--sources', the list of sources (files or buffers to
annotate).")

;; Add a preset meant for calling from the prompt using @gptel-annotate
(apply #'gptel-make-preset 'gptel-annotate
       :pre #'gptel-annotate--pre gptel-annotate--preset)

;;;###autoload
(defun gptel-annotate (sources prompt)
  "Annotate SOURCES (files or buffers) with LLM suggestions.

SOURCES is the current buffer by default.  If `prefix-arg' is set, query
for buffers and files to annotate instead.  Multiple buffers and files
can be specified.

PROMPT contains the instructions, read from the buffer at point (like
`gptel-send') or explicitly provided.

The annotations are displayed using flymake."
  (interactive
   (let ((source-bufs
          (if current-prefix-arg
              (completing-read-multiple "Annotate buffer(s) (empty for none):"
                                        (mapcar #'buffer-name (buffer-list)) nil t)
            (list (buffer-name))))
         (source-files
          (and current-prefix-arg
               (completing-read-multiple "Annotate file(s) (empty for none): "
                                         #'read-file-name-internal nil t)))
         (p (read-string "Instructions for annotating \
(leave empty to read from conversation at point): ")))
     (list (nconc (mapcar #'get-buffer source-bufs) source-files)
           (if (string-blank-p p) nil p))))
  (unless sources
    (user-error "No sources (files or buffers) specified, canceling gptel-annotate"))
  (let ((gptel-annotate--sources sources)
        (fsm (gptel-make-fsm
              :table gptel-send--transitions
              :handlers gptel-send--handlers)))
    (gptel-with-preset gptel-annotate--preset
      (gptel-request prompt
        ;; FIXME: :schema cannot be applied via `gptel-with-preset'
        :schema gptel-annotate-response-schema
        :stream gptel-stream
        :transforms gptel-prompt-transform-functions
        :fsm fsm))
    ;; Assume that unless we are in a chat buffer, it's not safe to insert the
    ;; response accoutrements (like the reasoning text) here.
    (let ((info (gptel-fsm-info fsm)))
      (unless (buffer-local-value 'gptel-mode (plist-get info :buffer))
        (with-current-buffer (get-buffer-create gptel-annotate--response-buffer)
          (goto-char (point-max)) (insert "\n\n")
          (move-marker (plist-get info :position) (point) (current-buffer)))))
    (message "Querying %s for annotations..."
             (thread-first (gptel-fsm-info fsm)
                           (plist-get :backend)
                           (or gptel-backend)
                           (gptel-backend-name)))
    (gptel--update-status " Waiting..." 'warning)))

(provide 'gptel-annotate)
;;; gptel-annotate.el ends here

;; Local Variables:
;; elisp-flymake-byte-compile-load-path: ("./" "../elpaca/repos/gptel/" "../elpaca/repos/transient/")
;; End:
